# Generated by Django 3.2.4 on 2021-07-29 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('past_address', models.CharField(max_length=200)),
                ('present_address', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
                ('created_user', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'profile_data',
            },
        ),
    ]
